"""Fixture-backed store for ARCH_MOCK=1 — identical Contract C shapes, no engine needed.

Backed by fixtures/mock/*.json (generated by tools/make_fixtures.py). Author merges are
in-memory only. Fixtures carry the repository object, root children, authors, commits
and the weekly series; deeper drill-downs are served as zeros-only stubs.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
FIX = ROOT / "fixtures" / "mock"
_merges: dict[str, str] = {}


def _load(name: str):
    path = FIX / name
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def repos() -> list:
    return _load("repos.json") or []


def repo(repo_id: str) -> dict | None:
    return _load(f"repo_{repo_id}.json")


def _stub_metrics(repo_id: str, otype: str, path: str) -> dict:
    return {
        "object": {"type": otype, "path": path},
        "commit_set": {"count": (repo(repo_id) or {}).get("commit_count", 0),
                       "from": None, "to": None, "commits": None},
        "all": {"added": 0, "removed": 0, "growth": 0, "churn": 0, "modifications": 0,
                "modification_frequency": 0.0, "churn_rate": 0.0, "ownership": None},
        "authors": [],
    }


def object_metrics(repo_id: str, path: str = "/", from_ts=None, to_ts=None,
                   commits=None, author=None) -> dict | None:
    path = path or "/"
    if path == "/":
        data = _load(f"metrics_repository_{repo_id}.json")
        if data is None:
            return None
        data = json.loads(json.dumps(data))  # copy
        if author:
            data["authors"] = [a for a in data["authors"] if a["author"] == author]
        return data
    source = _load(f"children_root_{repo_id}.json") or []
    for item in source:
        if item["path"] == path:
            otype = "directory" if item["type"] == "dir" else "file"
            stub = _stub_metrics(repo_id, otype, path)
            stub["all"].update({k: item.get(k) for k in
                                ("added", "removed", "growth", "churn", "modifications",
                                 "modification_frequency", "churn_rate")})
            return stub
    return None


def children(repo_id: str, dir_path: str = "/", from_ts=None, to_ts=None, commits=None,
             author=None, sort: str = "churn", order: str = "desc") -> list:
    if dir_path not in ("/", ""):
        return []
    items = _load(f"children_root_{repo_id}.json") or []
    items = [dict(i) for i in items]
    key = sort if sort in ("churn", "growth", "added", "removed", "modifications") else "churn"
    if sort == "name":
        items.sort(key=lambda x: x["name"].lower(), reverse=(order == "desc"))
    else:
        items.sort(key=lambda x: (x.get(key) or 0, x["name"]), reverse=(order != "asc"))
    return items


def series(repo_id: str, path: str = "/", bucket: str = "week", from_ts=None, to_ts=None,
           commits=None) -> list:
    if path not in ("/", ""):
        return []
    return _load(f"series_repository_{repo_id}.json") or []


def repo_authors(repo_id: str, from_ts=None, to_ts=None, commits=None) -> list:
    data = _load(f"metrics_repository_{repo_id}.json")
    if data is None:
        return []
    return data["authors"]


def commits_list(repo_id: str, limit: int = 100, offset: int = 0, q: str | None = None,
                 from_ts=None, to_ts=None) -> list:
    data = _load(f"commits_{repo_id}.json") or []
    if from_ts is not None:
        data = [c for c in data if c["ct"] >= from_ts]
    if to_ts is not None:
        data = [c for c in data if c["ct"] < to_ts]
    if q:
        ql = q.lower()
        data = [c for c in data
                if ql in c["author"].lower() or ql in (c.get("subject") or "").lower()]
    return data[offset:offset + limit]


def repo_counts(repo_id: str) -> dict:
    detail = repo(repo_id) or {}
    return {"authors_count": detail.get("authors_count"),
            "files_count": detail.get("files_count"),
            "dirs_count": detail.get("dirs_count")}


def list_merges(repo_id: str | None = None) -> dict:
    return dict(_merges)


def set_merge(repo_id: str, raws: list, target: str) -> dict:
    for raw in raws:
        if raw and raw != target:
            _merges[raw] = target
    return list_merges()


def unmerge(repo_id: str, raw: str | None = None, all_: bool = False) -> dict:
    if all_:
        _merges.clear()
    elif raw:
        _merges.pop(raw, None)
        for k in [k for k, v in _merges.items() if v == raw]:
            _merges.pop(k)
    return list_merges()


def mailmap_preview(repo_id: str) -> dict:
    return {"available": False, "entries": []}


def apply_mailmap(repo_id: str) -> dict:
    return {"applied": 0, "available": False, "entries": []}
